// The question bank.
//
// Three rules govern everything here:
//
//  1. Questions ask what happened, not how good it was. "What has the team
//     shipped in the last 12 months" is answerable from memory of events;
//     "how strong is your team" is answerable from ego.
//  2. Every answer carries an evidence class. Two founders can pick the same
//     option and get different confidence, because one measured it and one
//     remembered it.
//  3. The things that matter most are asked twice, from different angles,
//     under a shared `probe`. The engine compares the answers.
//
// Scores are never shown while answering, and the options are not ordered
// best-to-worst everywhere, so "pick the top one" is not a usable strategy.

import type { Question, SignalState } from "../types";

const has = (state: SignalState, key: string): boolean => Boolean(state[key]);
const num = (state: SignalState, key: string): number => {
  const value = state[key];
  return typeof value === "number" && isFinite(value) ? value : 0;
};

export const QUESTIONS: Question[] = [
  /* ── Company ──────────────────────────────────────────────────────── */
  {
    id: "stage_state",
    section: "company",
    kind: "single",
    core: true,
    prompt: "Which of these is true of your product today?",
    helper: "Pick the furthest one that is already true — not the one you expect to be true next quarter.",
    evidence: "self_reported",
    contributes: [{ factor: "product", weight: 1.4 }, { factor: "traction", weight: 0.6 }],
    probe: "build_state",
    options: [
      {
        id: "concept",
        label: "It is a concept and a plan. Nothing has been built.",
        score: 0.15,
        signals: { stage: "idea", has_prototype: false, has_users: false, has_revenue: false },
      },
      {
        id: "prototype",
        label: "A prototype exists, but nobody outside the company has used it.",
        score: 0.35,
        signals: { stage: "prototype", has_prototype: true, has_users: false, has_revenue: false },
      },
      {
        id: "live_free",
        label: "People outside the company use it, but nobody pays.",
        score: 0.6,
        signals: { stage: "mvp", has_prototype: true, has_users: true, has_revenue: false },
      },
      {
        id: "paying",
        label: "Customers pay for it, and the payments repeat.",
        score: 0.85,
        signals: { stage: "revenue", has_prototype: true, has_users: true, has_revenue: true },
      },
      {
        id: "scaling",
        label: "Revenue is growing month over month on a channel we can repeat.",
        score: 1,
        signals: { stage: "scaling", has_prototype: true, has_users: true, has_revenue: true },
      },
    ],
  },
  {
    id: "sector",
    section: "company",
    kind: "single",
    core: true,
    prompt: "Which of these best describes what you sell?",
    helper: "This sets the comparable companies your valuation is anchored against.",
    evidence: "self_reported",
    contributes: [],
    options: [
      { id: "saas_b2b", label: "Software sold to businesses on a subscription", score: 0.5, signals: { sector: "saas_b2b" } },
      { id: "consumer", label: "A consumer app or service", score: 0.5, signals: { sector: "consumer" } },
      { id: "marketplace", label: "A marketplace connecting two sides", score: 0.5, signals: { sector: "marketplace" } },
      { id: "ecommerce", label: "Physical products sold direct", score: 0.5, signals: { sector: "ecommerce" } },
      { id: "deeptech", label: "Deep tech, hardware or biotech with a research core", score: 0.5, signals: { sector: "deeptech" } },
      { id: "fintech", label: "Financial services or fintech infrastructure", score: 0.5, signals: { sector: "fintech" } },
      { id: "services", label: "Services delivered by people, productised", score: 0.5, signals: { sector: "services" } },
    ],
  },
  {
    id: "geography",
    section: "company",
    kind: "single",
    core: true,
    prompt: "Where do you bill your customers from, and where are they?",
    helper: "Valuation comparables are regional. A seed round in one market is not priced like the same company in another.",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 0.4 }],
    options: [
      { id: "us", label: "Mostly the United States", score: 0.5, signals: { geography: "United States" } },
      { id: "uk_eu", label: "Mostly the UK or Western Europe", score: 0.5, signals: { geography: "UK / Western Europe" } },
      { id: "cee_cis", label: "Mostly Central/Eastern Europe, Caucasus or Central Asia", score: 0.5, signals: { geography: "CEE / CIS / Caucasus" } },
      { id: "mena_apac", label: "Mostly the Middle East, Africa or Asia-Pacific", score: 0.5, signals: { geography: "MENA / APAC" } },
      { id: "latam", label: "Mostly Latin America", score: 0.5, signals: { geography: "Latin America" } },
      { id: "spread", label: "Spread across several regions with no clear home market", score: 0.5, signals: { geography: "multi-region" } },
    ],
  },
  {
    id: "months_active",
    section: "company",
    kind: "number",
    core: true,
    prompt: "How many months has anyone worked on this full-time?",
    helper: "Count from the first month someone was working on it as their main occupation. Zero is a valid answer.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.5 }],
    numeric: {
      unit: "months",
      placeholder: "e.g. 14",
      min: 0,
      max: 240,
      signal: "months_active",
      buckets: [
        { max: 2, score: 0.25, label: "Just started" },
        { max: 6, score: 0.45, label: "Under six months" },
        { max: 18, score: 0.8, label: "Six to eighteen months" },
        { max: 42, score: 1, label: "Eighteen months to three and a half years" },
        { max: Infinity, score: 0.7, label: "Over three and a half years" },
      ],
    },
  },
  {
    id: "legal_base",
    section: "company",
    kind: "single",
    prompt: "How is ownership of the company and its IP currently held?",
    helper: "Investors check this before anything else, and it is cheap to get wrong.",
    evidence: "documented",
    contributes: [{ factor: "financial", weight: 0.6 }, { factor: "relationships", weight: 0.4 }],
    options: [
      { id: "clean", label: "Incorporated, cap table documented, IP assigned to the company", score: 1, evidence: "verified" },
      { id: "incorporated", label: "Incorporated, but IP assignment or the cap table is unfinished", score: 0.6 },
      { id: "informal", label: "Incorporated with an informal split agreed verbally", score: 0.35, evidence: "self_reported" },
      { id: "none", label: "Not incorporated yet", score: 0.15, signals: { not_incorporated: true } },
    ],
  },

  /* ── Team ─────────────────────────────────────────────────────────── */
  {
    id: "team_track",
    section: "team",
    kind: "single",
    core: true,
    prompt: "What has the founding team actually completed in the last 12 months?",
    helper: "The furthest point you reached, not the furthest point you planned.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 1.5 }, { factor: "product", weight: 0.5 }],
    probe: "build_state",
    options: [
      { id: "launched_paid", label: "Built and launched a product that paying customers now use", score: 1, signals: { claims_paying_launch: true } },
      { id: "mvp_users", label: "Built a working MVP with active users", score: 0.75, signals: { claims_live_users: true } },
      { id: "prototype", label: "Built a prototype, no external users yet", score: 0.5 },
      { id: "concept", label: "Developed the concept, research and plan", score: 0.25 },
      { id: "pivoted", label: "Rebuilt after a pivot — the current direction is a few months old", score: 0.45, signals: { recent_pivot: true } },
    ],
  },
  {
    id: "team_fulltime",
    section: "team",
    kind: "number",
    core: true,
    prompt: "How many founders work on this full-time, drawing no other salary?",
    helper: "Full-time means this is their job, not their evenings.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 1.2 }],
    probe: "commitment",
    numeric: {
      unit: "founders",
      placeholder: "e.g. 2",
      min: 0,
      max: 10,
      signal: "founders_fulltime",
      buckets: [
        { max: 0, score: 0.1, label: "None full-time" },
        { max: 1, score: 0.6, label: "One full-time founder" },
        { max: 3, score: 1, label: "Two or three full-time founders" },
        { max: Infinity, score: 0.75, label: "Four or more full-time founders" },
      ],
    },
  },
  {
    id: "team_commitment",
    section: "team",
    kind: "single",
    core: true,
    prompt: "What did the founders give up to work on this?",
    helper: "Commitment shows up in what was traded away, not in what was promised.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.9 }],
    probe: "commitment",
    options: [
      { id: "left_jobs", label: "Left salaried jobs; this is the only source of income", score: 1, signals: { commitment_level: 3 } },
      { id: "reduced", label: "Went part-time elsewhere to make room for this", score: 0.6, signals: { commitment_level: 2 } },
      { id: "savings", label: "Kept jobs but put personal capital in", score: 0.5, signals: { commitment_level: 2 } },
      { id: "side", label: "It runs alongside full-time employment", score: 0.25, signals: { commitment_level: 1 } },
    ],
  },
  {
    id: "team_technical",
    section: "team",
    kind: "single",
    core: true,
    prompt: "Who builds the core product?",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 1 }, { factor: "technology", weight: 0.7 }],
    options: [
      { id: "founder", label: "A founder, hands-on, with equity", score: 1, signals: { has_technical_founder: true } },
      { id: "employee", label: "An employee we hired for it", score: 0.75, signals: { has_technical_founder: false } },
      { id: "agency", label: "An outsourced agency or contractors", score: 0.4, signals: { has_technical_founder: false, outsourced_build: true } },
      { id: "nobody", label: "Nobody yet — we are looking for this person", score: 0.15, signals: { has_technical_founder: false, technical_gap: true } },
      { id: "no_code", label: "It is assembled on no-code tooling by a non-technical founder", score: 0.45, signals: { has_technical_founder: false } },
    ],
  },
  {
    id: "team_prior",
    section: "team",
    kind: "single",
    core: true,
    prompt: "Has anyone on the founding team taken a product from nothing to paying customers before?",
    evidence: "documented",
    contributes: [{ factor: "team", weight: 1.1 }],
    probe: "team_experience",
    options: [
      { id: "exit", label: "Yes, at a company they founded that was later acquired or is still operating", score: 1, evidence: "verified", signals: { prior_founder: true } },
      { id: "founded_failed", label: "Yes, at a company they founded that has since shut down", score: 0.8, signals: { prior_founder: true } },
      { id: "employee_early", label: "Yes, as an early employee, not as a founder", score: 0.65 },
      { id: "shipped_corp", label: "They shipped products inside a larger company", score: 0.5 },
      { id: "first", label: "No — this is the first time for everyone involved", score: 0.25, signals: { first_time_team: true } },
    ],
  },
  {
    id: "team_domain",
    section: "team",
    kind: "single",
    core: true,
    prompt: "Where does the team's knowledge of this specific problem come from?",
    helper: "How you learned the problem predicts how many surprises are left in it.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 1 }, { factor: "market", weight: 0.5 }],
    probe: "team_experience",
    options: [
      { id: "lived", label: "We had this job and this problem ourselves, for years", score: 1, signals: { domain_source: "lived" } },
      { id: "worked_adjacent", label: "We worked in the industry, adjacent to the problem", score: 0.8, signals: { domain_source: "adjacent" } },
      { id: "research", label: "Academic or research work on this problem", score: 0.75, signals: { domain_source: "research" } },
      { id: "interviews", label: "We learned it by interviewing people who have it", score: 0.55, signals: { domain_source: "interviews" } },
      { id: "outside", label: "We came to it from outside the industry, on the market opportunity", score: 0.35, signals: { domain_source: "outside" } },
    ],
  },
  {
    id: "team_gaps",
    section: "team",
    kind: "multi",
    prompt: "Which of these does the team currently have covered, in-house and full-time?",
    helper: "Select every one that is genuinely covered today. An advisor does not count.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.8 }],
    multi: { noneOption: "none" },
    options: [
      { id: "engineering", label: "Engineering", score: 1 },
      { id: "design", label: "Product and design", score: 1 },
      { id: "sales", label: "Sales or business development", score: 1 },
      { id: "domain", label: "Deep domain or regulatory expertise", score: 1 },
      { id: "finance", label: "Finance and operations", score: 1 },
      { id: "none", label: "None of these are covered full-time yet", score: 0, signals: { no_functions_covered: true } },
    ],
  },
  {
    id: "team_retention",
    section: "team",
    kind: "single",
    when: (s) => num(s, "months_active") >= 9,
    prompt: "Has anyone left the founding team since you started?",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.6 }],
    options: [
      { id: "none", label: "No — the founding team is intact", score: 1 },
      { id: "one_clean", label: "One person left, with equity settled cleanly", score: 0.65 },
      { id: "one_open", label: "One person left and the equity is still unresolved", score: 0.2, signals: { cap_table_risk: true } },
      { id: "several", label: "More than one person has left", score: 0.25, signals: { cap_table_risk: true } },
    ],
  },

  /* ── Market ───────────────────────────────────────────────────────── */
  {
    id: "market_basis",
    section: "market",
    kind: "single",
    core: true,
    prompt: "Where does your market size figure come from?",
    helper: "The source matters more than the number. We weight the number by how it was produced.",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 1.3 }],
    probe: "market_rigour",
    options: [
      { id: "official", label: "Government or official statistics", score: 0.95, evidence: "verified", signals: { market_basis: "official" } },
      { id: "report", label: "A paid industry research report", score: 0.9, evidence: "documented", signals: { market_basis: "report" } },
      { id: "public_co", label: "Public company filings and disclosed revenues", score: 0.85, evidence: "documented", signals: { market_basis: "public_co" } },
      { id: "bottom_up", label: "Bottom-up: our own count of buyers times a price we have tested", score: 1, evidence: "documented", signals: { market_basis: "bottom_up" } },
      { id: "interviews", label: "Extrapolated from customer interviews we ran", score: 0.6, evidence: "self_reported", signals: { market_basis: "interviews" } },
      { id: "estimate", label: "Our own estimate, from reading and judgement", score: 0.3, evidence: "estimated", signals: { market_basis: "estimate" } },
    ],
  },
  {
    id: "market_sam",
    section: "market",
    kind: "number",
    core: true,
    prompt: "In dollars per year, how much do the customers you can actually reach spend on this problem today?",
    helper: "Not the global market — the segment you could sell to within about three years.",
    evidence: "estimated",
    contributes: [{ factor: "market", weight: 1 }],
    numeric: {
      unit: "USD / year",
      placeholder: "e.g. 40000000",
      min: 0,
      signal: "sam_usd",
      buckets: [
        { max: 5_000_000, score: 0.3, label: "Under $5M" },
        { max: 50_000_000, score: 0.6, label: "$5M – $50M" },
        { max: 500_000_000, score: 0.9, label: "$50M – $500M" },
        { max: 5_000_000_000, score: 1, label: "$500M – $5B" },
        { max: Infinity, score: 0.75, label: "Over $5B" },
      ],
    },
  },
  {
    id: "market_buyers",
    section: "market",
    kind: "single",
    core: true,
    prompt: "How precisely can you describe the person who signs off on buying this?",
    helper: "A cross-check on the market figure: a real market has a nameable buyer.",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 1 }, { factor: "gtm", weight: 0.6 }],
    probe: "market_rigour",
    options: [
      { id: "named_list", label: "We have a named list of specific people and have spoken to many of them", score: 1, evidence: "documented" },
      { id: "role_precise", label: "We know the exact role and company profile, and have spoken to some", score: 0.8 },
      { id: "role_general", label: "We know the role in general terms", score: 0.5 },
      { id: "segment", label: "We can describe the segment but not the individual buyer", score: 0.3 },
      { id: "unclear", label: "It is not yet clear who signs off", score: 0.1, signals: { buyer_unclear: true } },
    ],
  },
  {
    id: "market_growth",
    section: "market",
    kind: "single",
    prompt: "What is happening to this market, and how do you know?",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 0.9 }],
    options: [
      { id: "growing_evidenced", label: "Growing quickly, and we can cite the data showing it", score: 1, evidence: "documented" },
      { id: "growing_belief", label: "Growing, we believe, based on what we see in the field", score: 0.65, evidence: "self_reported" },
      { id: "stable", label: "Stable in size — the opportunity is taking share, not riding growth", score: 0.5 },
      { id: "new", label: "The market does not exist yet; we would be creating it", score: 0.45, signals: { creating_market: true } },
      { id: "declining", label: "Shrinking, and we are betting on a specific structural change", score: 0.3 },
    ],
  },
  {
    id: "market_timing",
    section: "market",
    kind: "single",
    prompt: "What changed recently that makes this possible now and not three years ago?",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 0.7 }, { factor: "technology", weight: 0.4 }],
    options: [
      { id: "regulation", label: "A regulatory change opened it up", score: 0.9, evidence: "documented" },
      { id: "tech", label: "A technology became cheap or capable enough", score: 0.9 },
      { id: "behaviour", label: "Customer behaviour shifted measurably", score: 0.8 },
      { id: "cost", label: "A cost curve crossed a threshold that makes the economics work", score: 0.85 },
      { id: "nothing", label: "Nothing in particular changed — it has simply not been built well", score: 0.35, signals: { no_timing_catalyst: true } },
    ],
  },

  /* ── Product & technology ─────────────────────────────────────────── */
  {
    id: "product_external_use",
    section: "product",
    kind: "single",
    core: true,
    prompt: "Who has used the product, and under what conditions?",
    evidence: "self_reported",
    contributes: [{ factor: "product", weight: 1.2 }, { factor: "traction", weight: 0.5 }],
    probe: "build_state",
    options: [
      { id: "production", label: "Customers use it unsupervised, in production, daily", score: 1, signals: { external_usage: 4 } },
      { id: "pilots", label: "Customers use it in supervised pilots", score: 0.75, signals: { external_usage: 3 } },
      { id: "friendlies", label: "Friendly users and design partners have tried it", score: 0.5, signals: { external_usage: 2 } },
      { id: "demos", label: "It has only been demonstrated by us, to others", score: 0.3, signals: { external_usage: 1 } },
      { id: "internal", label: "Only the team has ever run it", score: 0.15, signals: { external_usage: 0 } },
    ],
  },
  {
    id: "product_completeness",
    section: "product",
    kind: "single",
    when: (s) => has(s, "has_prototype"),
    prompt: "If a new customer signed up today, what would they get?",
    evidence: "self_reported",
    contributes: [{ factor: "product", weight: 1 }],
    options: [
      { id: "self_serve", label: "A working product they can set up themselves", score: 1 },
      { id: "onboarded", label: "A working product, once we onboard them by hand", score: 0.75 },
      { id: "partial", label: "The core workflow, with gaps we fill manually behind the scenes", score: 0.5, signals: { manual_backend: true } },
      { id: "bespoke", label: "Something we would build largely for them", score: 0.3, signals: { bespoke_delivery: true } },
    ],
  },
  {
    id: "tech_difficulty",
    section: "product",
    kind: "single",
    prompt: "How long would a competent, funded team need to rebuild what you have?",
    helper: "An honest answer here is worth more than an optimistic one — we cross-check it against your moat ranking.",
    evidence: "estimated",
    contributes: [{ factor: "technology", weight: 1.2 }, { factor: "competition", weight: 0.5 }],
    probe: "defensibility",
    options: [
      { id: "years", label: "Years — it depends on research or data we spent years accumulating", score: 1, signals: { rebuild_effort: 4 } },
      { id: "many_months", label: "Six to twelve months of focused work", score: 0.75, signals: { rebuild_effort: 3 } },
      { id: "months", label: "A few months", score: 0.5, signals: { rebuild_effort: 2 } },
      { id: "weeks", label: "Weeks — the difficulty is not in the building", score: 0.3, signals: { rebuild_effort: 1 } },
    ],
  },
  {
    id: "tech_ip",
    section: "product",
    kind: "single",
    prompt: "What formal protection exists over the technology?",
    evidence: "documented",
    contributes: [{ factor: "technology", weight: 0.8 }, { factor: "competition", weight: 0.4 }],
    options: [
      { id: "granted", label: "Granted patents held by the company", score: 1, evidence: "verified", signals: { ip_position: "granted" } },
      { id: "filed", label: "Applications filed, none granted yet", score: 0.7, evidence: "verified", signals: { ip_position: "filed" } },
      { id: "trade_secret", label: "No filings — the advantage is in know-how we keep private", score: 0.5, evidence: "self_reported" },
      { id: "none", label: "Nothing formal, and nothing we consider protectable", score: 0.25, evidence: "self_reported" },
    ],
  },
  {
    id: "tech_dependency",
    section: "product",
    kind: "single",
    when: (s) => has(s, "has_prototype"),
    prompt: "If your largest third-party dependency tripled its price or closed its API, what happens?",
    evidence: "self_reported",
    contributes: [{ factor: "technology", weight: 0.7 }, { factor: "financial", weight: 0.3 }],
    options: [
      { id: "none", label: "No material dependency — we would carry on", score: 1 },
      { id: "swap", label: "We would swap it out in weeks; alternatives exist", score: 0.75 },
      { id: "painful", label: "It would take months and hurt margins", score: 0.4, signals: { platform_risk: true } },
      { id: "fatal", label: "The product does not work without it", score: 0.15, signals: { platform_risk: true, platform_risk_severe: true } },
    ],
  },

  /* ── Traction: pre-users branch ───────────────────────────────────── */
  {
    id: "validation_strongest",
    section: "traction",
    kind: "single",
    core: true,
    when: (s) => !has(s, "has_users"),
    prompt: "What is the strongest commitment anyone outside the company has made?",
    helper: "Ranked by cost to the person making it. Money is the most expensive signal, opinions the cheapest.",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 1.4 }, { factor: "market", weight: 0.6 }],
    options: [
      { id: "prepaid", label: "Someone has paid us money in advance", score: 1, evidence: "verified", signals: { prepaid: true } },
      { id: "signed_loi", label: "A signed letter of intent or pilot agreement", score: 0.8, evidence: "documented", signals: { has_loi: true } },
      { id: "verbal", label: "A verbal commitment to buy once it exists", score: 0.5, evidence: "self_reported" },
      { id: "waitlist", label: "People joined a waitlist or signed up for early access", score: 0.4, evidence: "documented" },
      { id: "enthusiasm", label: "People told us in interviews that they would use it", score: 0.25, evidence: "self_reported" },
      { id: "none", label: "No outside commitment yet", score: 0.05, signals: { no_external_validation: true } },
    ],
  },
  {
    id: "validation_interviews",
    section: "traction",
    kind: "number",
    when: (s) => !has(s, "has_users"),
    prompt: "How many potential customers have you had a real conversation with about this problem?",
    helper: "Conversations where they described their own problem — not ones where you presented your solution.",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 0.8 }, { factor: "traction", weight: 0.5 }],
    numeric: {
      unit: "conversations",
      placeholder: "e.g. 25",
      min: 0,
      signal: "interviews_count",
      buckets: [
        { max: 4, score: 0.1, label: "Almost none" },
        { max: 14, score: 0.4, label: "A handful" },
        { max: 39, score: 0.75, label: "Dozens" },
        { max: Infinity, score: 1, label: "Forty or more" },
      ],
    },
  },
  {
    id: "validation_record",
    section: "traction",
    kind: "single",
    when: (s) => !has(s, "has_users") && num(s, "interviews_count") > 0,
    prompt: "What record exists of those conversations?",
    evidence: "self_reported",
    contributes: [{ factor: "market", weight: 0.6 }],
    probe: "market_rigour",
    options: [
      { id: "transcripts", label: "Notes or transcripts for each one, in a shared document", score: 1, evidence: "documented" },
      { id: "summary", label: "A written summary of what we learned overall", score: 0.7, evidence: "documented" },
      { id: "memory", label: "They live in our heads and in scattered notes", score: 0.35, evidence: "self_reported" },
    ],
  },

  /* ── Traction: live-users branch ──────────────────────────────────── */
  {
    id: "users_total",
    section: "traction",
    kind: "number",
    core: true,
    when: (s) => has(s, "has_users"),
    prompt: "How many people have ever used the product?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 0.8 }],
    probe: "usage_scale",
    numeric: {
      unit: "users",
      placeholder: "e.g. 1200",
      min: 0,
      signal: "users_total",
      buckets: [
        { max: 20, score: 0.2, label: "Under 20" },
        { max: 200, score: 0.45, label: "20 – 200" },
        { max: 2_000, score: 0.7, label: "200 – 2,000" },
        { max: 20_000, score: 0.9, label: "2,000 – 20,000" },
        { max: Infinity, score: 1, label: "Over 20,000" },
      ],
    },
  },
  {
    id: "users_active",
    section: "traction",
    kind: "number",
    core: true,
    when: (s) => has(s, "has_users"),
    prompt: "How many used it in the last 30 days?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 1.1 }],
    probe: "usage_scale",
    numeric: {
      unit: "users",
      placeholder: "e.g. 340",
      min: 0,
      signal: "users_active",
      buckets: [
        { max: 5, score: 0.15, label: "Almost none" },
        { max: 50, score: 0.4, label: "Under 50" },
        { max: 500, score: 0.7, label: "50 – 500" },
        { max: 5_000, score: 0.9, label: "500 – 5,000" },
        { max: Infinity, score: 1, label: "Over 5,000" },
      ],
    },
  },
  {
    id: "usage_pattern",
    section: "traction",
    kind: "single",
    core: true,
    when: (s) => has(s, "has_users"),
    prompt: "Which pattern best describes how the product actually gets used?",
    evidence: "self_reported",
    contributes: [{ factor: "traction", weight: 1.2 }, { factor: "product", weight: 0.5 }],
    probe: "retention",
    options: [
      { id: "daily", label: "Most users come back on their own, several times a week", score: 1, signals: { usage_pattern: "habitual" } },
      { id: "weekly", label: "Users return for a recurring task, roughly weekly or monthly", score: 0.85, signals: { usage_pattern: "recurring" } },
      { id: "campaign", label: "Usage clusters around events or campaigns, then goes quiet", score: 0.55, signals: { usage_pattern: "episodic" } },
      { id: "prompted", label: "Users come back mainly when we contact them", score: 0.35, signals: { usage_pattern: "prompted" } },
      { id: "one_off", label: "Most people use it once and do not return", score: 0.15, signals: { usage_pattern: "one_off" } },
    ],
  },
  {
    id: "repeat_share",
    section: "traction",
    kind: "single",
    core: true,
    when: (s) => has(s, "has_users"),
    prompt: "Of everyone who has ever used it, roughly what share used it more than once?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 1.1 }],
    probe: "retention",
    options: [
      { id: "most", label: "Most of them — more than 60%", score: 1, signals: { repeat_ratio: 0.75 } },
      { id: "about_half", label: "Roughly half", score: 0.7, signals: { repeat_ratio: 0.5 } },
      { id: "quarter", label: "About a quarter", score: 0.45, signals: { repeat_ratio: 0.25 } },
      { id: "few", label: "Under 10%", score: 0.2, signals: { repeat_ratio: 0.08 } },
      { id: "unknown", label: "We do not measure this", score: 0.3, evidence: "absent", signals: { repeat_unmeasured: true } },
    ],
  },
  {
    id: "retention_measure",
    section: "traction",
    kind: "single",
    when: (s) => has(s, "has_users"),
    prompt: "How do you know your usage numbers?",
    helper: "This sets the evidence weight on everything you just told us about usage.",
    evidence: "self_reported",
    contributes: [{ factor: "traction", weight: 0.7 }],
    options: [
      { id: "analytics", label: "Product analytics we query directly", score: 1, evidence: "verified", signals: { usage_instrumented: true } },
      { id: "database", label: "Counted from our own database when asked", score: 0.85, evidence: "documented", signals: { usage_instrumented: true } },
      { id: "spreadsheet", label: "A spreadsheet we update manually", score: 0.55, evidence: "self_reported" },
      { id: "estimate", label: "Estimated — we do not track it precisely", score: 0.25, evidence: "estimated", signals: { usage_estimated: true } },
    ],
  },

  /* ── Traction: revenue branch ─────────────────────────────────────── */
  {
    id: "revenue_mrr",
    section: "traction",
    kind: "number",
    core: true,
    when: (s) => has(s, "has_revenue"),
    prompt: "What did you collect from customers last month, in dollars?",
    helper: "Money that actually arrived, excluding grants and investment.",
    evidence: "verified",
    contributes: [{ factor: "traction", weight: 1.3 }, { factor: "financial", weight: 0.5 }],
    numeric: {
      unit: "USD / month",
      placeholder: "e.g. 12000",
      min: 0,
      signal: "mrr_usd",
      buckets: [
        { max: 0, score: 0.05, label: "Nothing yet" },
        { max: 1_000, score: 0.35, label: "Under $1k" },
        { max: 10_000, score: 0.6, label: "$1k – $10k" },
        { max: 100_000, score: 0.85, label: "$10k – $100k" },
        { max: Infinity, score: 1, label: "Over $100k" },
      ],
    },
  },
  {
    id: "paying_customers",
    section: "traction",
    kind: "number",
    core: true,
    when: (s) => has(s, "has_revenue"),
    prompt: "How many separate customers paid you last month?",
    evidence: "verified",
    contributes: [{ factor: "traction", weight: 0.9 }],
    probe: "usage_scale",
    numeric: {
      unit: "customers",
      placeholder: "e.g. 18",
      min: 0,
      signal: "paying_customers",
      buckets: [
        { max: 0, score: 0.05, label: "None" },
        { max: 3, score: 0.4, label: "One to three" },
        { max: 20, score: 0.7, label: "Four to twenty" },
        { max: 200, score: 0.9, label: "Twenty to two hundred" },
        { max: Infinity, score: 1, label: "Over two hundred" },
      ],
    },
  },
  {
    id: "contract_value",
    section: "traction",
    kind: "number",
    when: (s) => has(s, "has_revenue"),
    prompt: "What does a typical customer pay you over a full year, in dollars?",
    helper: "The average across your customers, not your largest one.",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 0.6 }, { factor: "gtm", weight: 0.4 }],
    numeric: {
      unit: "USD / year",
      placeholder: "e.g. 7600",
      min: 0,
      signal: "acv_usd",
      buckets: [
        { max: 500, score: 0.35, label: "Under $500" },
        { max: 5_000, score: 0.6, label: "$500 - $5k" },
        { max: 50_000, score: 0.9, label: "$5k - $50k" },
        { max: Infinity, score: 1, label: "Over $50k" },
      ],
    },
  },
  {
    id: "revenue_evidence",
    section: "traction",
    kind: "single",
    core: true,
    when: (s) => has(s, "has_revenue"),
    prompt: "Where would that revenue figure be visible to someone outside the company?",
    evidence: "self_reported",
    contributes: [{ factor: "traction", weight: 0.8 }, { factor: "financial", weight: 0.6 }],
    options: [
      { id: "bank", label: "Bank statements and a payment processor dashboard", score: 1, evidence: "verified", signals: { revenue_verifiable: true } },
      { id: "invoices", label: "Issued invoices with matching payments", score: 0.9, evidence: "verified", signals: { revenue_verifiable: true } },
      { id: "contracts", label: "Signed contracts, with the first payments due later", score: 0.6, evidence: "documented", signals: { revenue_contracted_only: true } },
      { id: "informal", label: "Informal payments, not fully documented", score: 0.35, evidence: "self_reported", signals: { revenue_informal: true } },
    ],
  },
  {
    id: "revenue_growth",
    section: "traction",
    kind: "single",
    when: (s) => has(s, "has_revenue"),
    prompt: "Comparing last month to three months ago, what happened to revenue?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 1 }],
    options: [
      { id: "doubled", label: "It more than doubled", score: 1, signals: { growth_band: 4 } },
      { id: "grew", label: "It grew, by something between 20% and 100%", score: 0.85, signals: { growth_band: 3 } },
      { id: "flat_up", label: "It grew slightly, under 20%", score: 0.6, signals: { growth_band: 2 } },
      { id: "flat", label: "It was flat", score: 0.4, signals: { growth_band: 1 } },
      { id: "down", label: "It fell", score: 0.2, signals: { growth_band: 0 } },
      { id: "too_new", label: "We have not been charging for three months yet", score: 0.45, evidence: "self_reported", signals: { revenue_too_new: true } },
    ],
  },
  {
    id: "churn",
    section: "traction",
    kind: "single",
    when: (s) => has(s, "has_revenue"),
    prompt: "Of the customers paying you six months ago, how many still pay you?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 1 }, { factor: "product", weight: 0.4 }],
    options: [
      { id: "all", label: "All of them, and several pay more than they did", score: 1, signals: { retention_band: 4 } },
      { id: "most", label: "Most of them", score: 0.8, signals: { retention_band: 3 } },
      { id: "half", label: "About half", score: 0.45, signals: { retention_band: 2 } },
      { id: "few", label: "Few of them", score: 0.15, signals: { retention_band: 1 } },
      { id: "na", label: "We have not been selling for six months", score: 0.5, evidence: "self_reported", signals: { retention_band: -1 } },
    ],
  },
  {
    id: "revenue_concentration",
    section: "traction",
    kind: "single",
    when: (s) => has(s, "has_revenue"),
    prompt: "What share of revenue comes from your single largest customer?",
    evidence: "documented",
    contributes: [{ factor: "traction", weight: 0.6 }, { factor: "financial", weight: 0.5 }],
    options: [
      { id: "under_10", label: "Under 10%", score: 1 },
      { id: "under_30", label: "Between 10% and 30%", score: 0.8 },
      { id: "under_60", label: "Between 30% and 60%", score: 0.45, signals: { concentration_risk: true } },
      { id: "over_60", label: "More than 60%", score: 0.15, signals: { concentration_risk: true, concentration_severe: true } },
    ],
  },
  {
    id: "gross_margin",
    section: "traction",
    kind: "single",
    when: (s) => has(s, "has_revenue"),
    prompt: "Of every $100 a customer pays, how much is left after the direct cost of serving them?",
    evidence: "documented",
    contributes: [{ factor: "financial", weight: 1 }],
    options: [
      { id: "high", label: "More than $75", score: 1, signals: { gross_margin_band: 4 } },
      { id: "good", label: "$50 to $75", score: 0.8, signals: { gross_margin_band: 3 } },
      { id: "medium", label: "$25 to $50", score: 0.5, signals: { gross_margin_band: 2 } },
      { id: "low", label: "Under $25", score: 0.25, signals: { gross_margin_band: 1 } },
      { id: "unknown", label: "We have not worked this out", score: 0.3, evidence: "absent", signals: { margin_unknown: true } },
    ],
  },

  /* ── Go-to-market ─────────────────────────────────────────────────── */
  {
    id: "channel_repeatable",
    section: "gtm",
    kind: "single",
    core: true,
    prompt: "Where did your last handful of users or customers come from?",
    evidence: "self_reported",
    contributes: [{ factor: "gtm", weight: 1.3 }],
    options: [
      { id: "paid_scaled", label: "A paid channel we can turn up, with known economics", score: 1, signals: { channel_known: true } },
      { id: "organic_repeat", label: "Inbound or organic that arrives predictably each week", score: 0.95, signals: { channel_known: true } },
      { id: "outbound", label: "Outbound we run ourselves, with a measured hit rate", score: 0.8, signals: { channel_known: true } },
      { id: "referral", label: "Existing customers referring new ones", score: 0.85, signals: { channel_known: true } },
      { id: "network", label: "Our personal networks", score: 0.35, signals: { channel_network_only: true } },
      { id: "one_off", label: "One-off events, launches or press", score: 0.3 },
    ],
  },
  {
    id: "cac_known",
    section: "gtm",
    kind: "single",
    when: (s) => has(s, "has_users"),
    prompt: "What does it cost you to acquire one customer, and how do you know?",
    evidence: "self_reported",
    contributes: [{ factor: "gtm", weight: 1 }, { factor: "financial", weight: 0.4 }],
    options: [
      { id: "measured", label: "We know it from spend divided by customers acquired, tracked monthly", score: 1, evidence: "documented", signals: { cac_known: true } },
      { id: "rough", label: "We have a rough figure from one or two campaigns", score: 0.6, evidence: "self_reported", signals: { cac_known: true } },
      { id: "no_spend", label: "We have not spent anything on acquisition yet", score: 0.4, evidence: "self_reported", signals: { cac_no_spend: true } },
      { id: "unknown", label: "We do not know", score: 0.15, evidence: "absent", signals: { cac_unknown: true } },
    ],
  },
  {
    id: "ltv_cac",
    section: "gtm",
    kind: "single",
    when: (s) => has(s, "cac_known") && has(s, "has_revenue"),
    prompt: "Over the life of a customer, how does what they pay compare with what they cost to acquire?",
    evidence: "documented",
    contributes: [{ factor: "gtm", weight: 1 }, { factor: "financial", weight: 0.7 }],
    options: [
      { id: "over_3", label: "They pay us more than three times what they cost", score: 1, signals: { ltv_cac_band: 3 } },
      { id: "two_three", label: "Between two and three times", score: 0.8, signals: { ltv_cac_band: 2 } },
      { id: "one_two", label: "Between one and two times", score: 0.45, signals: { ltv_cac_band: 1 } },
      { id: "under_one", label: "Less than they cost to acquire", score: 0.15, signals: { ltv_cac_band: 0 } },
      { id: "too_early", label: "Too early to say — we do not have a lifetime yet", score: 0.4, evidence: "estimated", signals: { ltv_cac_band: -1 } },
    ],
  },
  {
    id: "cac_amount",
    section: "gtm",
    kind: "number",
    when: (s) => has(s, "cac_known"),
    prompt: "In dollars, what does one new customer cost you to win?",
    helper: "Everything spent on acquisition in a period, divided by the customers it produced.",
    evidence: "documented",
    contributes: [{ factor: "gtm", weight: 0.8 }, { factor: "financial", weight: 0.3 }],
    numeric: {
      unit: "USD / customer",
      placeholder: "e.g. 900",
      min: 0,
      signal: "cac_usd",
      buckets: [
        { max: 100, score: 1, label: "Under $100" },
        { max: 1_000, score: 0.85, label: "$100 - $1k" },
        { max: 10_000, score: 0.6, label: "$1k - $10k" },
        { max: Infinity, score: 0.4, label: "Over $10k" },
      ],
    },
  },
  {
    id: "sales_cycle",
    section: "gtm",
    kind: "single",
    when: (s) => s.sector === "saas_b2b" || s.sector === "fintech" || s.sector === "deeptech" || s.sector === "services",
    prompt: "From first contact to signed deal, how long does it take?",
    evidence: "self_reported",
    contributes: [{ factor: "gtm", weight: 0.8 }],
    options: [
      { id: "days", label: "Days — they can buy without approval", score: 1 },
      { id: "weeks", label: "A few weeks", score: 0.85 },
      { id: "quarter", label: "One to two quarters", score: 0.55 },
      { id: "long", label: "More than six months, with procurement involved", score: 0.3, signals: { long_sales_cycle: true } },
      { id: "unknown", label: "We have not closed enough deals to know", score: 0.25, evidence: "absent" },
    ],
  },

  /* ── Competition ──────────────────────────────────────────────────── */
  {
    id: "competitors_named",
    section: "competition",
    kind: "single",
    core: true,
    prompt: "How many companies could a customer buy from instead of you?",
    helper: "Count anything a buyer would consider, including doing nothing and doing it in a spreadsheet.",
    evidence: "self_reported",
    contributes: [{ factor: "competition", weight: 1.2 }, { factor: "market", weight: 0.4 }],
    probe: "competitive_awareness",
    options: [
      { id: "many_known", label: "Many — we track a named list and know how we differ from each", score: 0.85, evidence: "documented" },
      { id: "few_direct", label: "Two or three direct ones we know well", score: 1 },
      { id: "indirect", label: "No direct competitor, but customers solve it manually today", score: 0.75 },
      { id: "none", label: "None — nobody else is doing this", score: 0.2, signals: { claims_no_competition: true } },
      { id: "dont_know", label: "We have not researched this properly", score: 0.15, evidence: "absent", signals: { competition_unresearched: true } },
    ],
  },
  {
    id: "alternative_today",
    section: "competition",
    kind: "single",
    core: true,
    prompt: "What do the people you have spoken to use today, before you exist?",
    helper: "Asked separately from the competitor question, because the honest answer to this one is rarely 'nothing'.",
    evidence: "self_reported",
    contributes: [{ factor: "competition", weight: 1 }, { factor: "market", weight: 0.5 }],
    probe: "competitive_awareness",
    options: [
      { id: "named_product", label: "A specific product we can name, and we know what they pay for it", score: 1, evidence: "documented" },
      { id: "spreadsheets", label: "Spreadsheets and manual process", score: 0.85 },
      { id: "agency", label: "They pay people — an agency, a contractor, internal staff", score: 0.85 },
      { id: "inhouse", label: "Something built internally at their own company", score: 0.7 },
      { id: "nothing", label: "Nothing — they live with the problem", score: 0.45, signals: { no_current_alternative: true } },
      { id: "unknown", label: "We do not know what they do today", score: 0.1, evidence: "absent", signals: { competition_unresearched: true } },
    ],
  },
  {
    id: "competitor_copy",
    section: "competition",
    kind: "single",
    core: true,
    prompt: "A well-funded competitor copies your product exactly, next quarter. What keeps your customers?",
    evidence: "self_reported",
    contributes: [{ factor: "competition", weight: 1.2 }, { factor: "technology", weight: 0.4 }],
    probe: "defensibility",
    options: [
      { id: "switching", label: "Their data and workflows live in our product; moving is expensive", score: 1, signals: { moat_type: "switching" } },
      { id: "network", label: "The product is worth more to them because other users are on it", score: 1, signals: { moat_type: "network" } },
      { id: "data", label: "We have accumulated data they cannot get without our history", score: 0.9, signals: { moat_type: "data" } },
      { id: "relationship", label: "Contracts and relationships we hold", score: 0.65, signals: { moat_type: "relationship" } },
      { id: "speed", label: "We would out-build them", score: 0.35, signals: { moat_type: "speed" } },
      { id: "nothing", label: "Honestly, not much", score: 0.15, signals: { moat_type: "none" } },
    ],
  },
  {
    id: "moat_rank",
    section: "competition",
    kind: "rank",
    prompt: "Put these in order of how much each one actually protects you today.",
    helper: "Order by what is true now, not what the plan says will be true later.",
    evidence: "self_reported",
    contributes: [{ factor: "competition", weight: 1 }, { factor: "technology", weight: 0.5 }],
    probe: "defensibility",
    rank: {
      items: [
        { id: "network_effects", label: "Network effects" },
        { id: "proprietary_data", label: "Proprietary data" },
        { id: "switching_costs", label: "Switching costs" },
        { id: "technology", label: "Technical difficulty" },
        { id: "brand", label: "Brand and trust" },
        { id: "execution_speed", label: "Speed of execution" },
      ],
      // Score for the item, given the position it is placed in. Ranking a
      // durable moat first is worth more than ranking speed first.
      positionScores: {
        network_effects: [1, 0.9, 0.8, 0.7, 0.6, 0.55],
        proprietary_data: [0.95, 0.88, 0.78, 0.68, 0.6, 0.55],
        switching_costs: [0.95, 0.88, 0.78, 0.68, 0.6, 0.55],
        technology: [0.8, 0.75, 0.7, 0.62, 0.58, 0.55],
        brand: [0.55, 0.55, 0.58, 0.6, 0.6, 0.6],
        execution_speed: [0.3, 0.36, 0.45, 0.55, 0.62, 0.7],
      },
    },
  },
  {
    id: "win_loss",
    section: "competition",
    kind: "single",
    when: (s) => has(s, "has_revenue"),
    prompt: "When you lose a deal, what is the usual reason?",
    evidence: "self_reported",
    contributes: [{ factor: "competition", weight: 0.8 }, { factor: "gtm", weight: 0.4 }],
    options: [
      { id: "budget", label: "Budget or timing — they wanted it but could not buy now", score: 0.85 },
      { id: "features", label: "A specific missing feature we know about", score: 0.7 },
      { id: "competitor", label: "They chose a competitor", score: 0.4 },
      { id: "status_quo", label: "They decided to keep doing it the way they already do", score: 0.35, signals: { loses_to_status_quo: true } },
      { id: "unknown", label: "We do not ask, so we do not know", score: 0.2, evidence: "absent" },
    ],
  },

  /* ── Financials ───────────────────────────────────────────────────── */
  {
    id: "runway",
    section: "financials",
    kind: "number",
    core: true,
    prompt: "At today's spending, how many months of cash are left?",
    evidence: "documented",
    contributes: [{ factor: "financial", weight: 1.2 }],
    numeric: {
      unit: "months",
      placeholder: "e.g. 9",
      min: 0,
      max: 120,
      signal: "runway_months",
      buckets: [
        { max: 3, score: 0.15, label: "Under three months" },
        { max: 6, score: 0.4, label: "Three to six months" },
        { max: 12, score: 0.75, label: "Six to twelve months" },
        { max: 24, score: 1, label: "One to two years" },
        { max: Infinity, score: 0.9, label: "Over two years" },
      ],
    },
  },
  {
    id: "burn",
    section: "financials",
    kind: "number",
    core: true,
    prompt: "How much does the company spend in a typical month, in dollars?",
    helper: "Everything that leaves the account, including founder salaries if you take them.",
    evidence: "documented",
    contributes: [{ factor: "financial", weight: 0.6 }],
    numeric: {
      unit: "USD / month",
      placeholder: "e.g. 18000",
      min: 0,
      signal: "burn_usd",
      buckets: [
        { max: 2_000, score: 0.7, label: "Under $2k" },
        { max: 20_000, score: 0.9, label: "$2k – $20k" },
        { max: 100_000, score: 0.7, label: "$20k – $100k" },
        { max: Infinity, score: 0.5, label: "Over $100k" },
      ],
    },
  },
  {
    id: "funding_history",
    section: "financials",
    kind: "single",
    core: true,
    prompt: "What money has gone into the company so far?",
    evidence: "documented",
    contributes: [{ factor: "financial", weight: 0.8 }, { factor: "relationships", weight: 0.8 }],
    options: [
      { id: "institutional", label: "Institutional investors — a fund has put money in", score: 1, evidence: "verified", signals: { prior_funding: "institutional" } },
      { id: "angel", label: "Angels or an accelerator", score: 0.85, evidence: "verified", signals: { prior_funding: "angel" } },
      { id: "grant", label: "Grants or non-dilutive public funding", score: 0.75, evidence: "verified", signals: { prior_funding: "grant" } },
      { id: "revenue", label: "Nothing outside — it is funded by its own revenue", score: 0.7, signals: { prior_funding: "revenue" } },
      { id: "founders", label: "Founder savings only", score: 0.4, signals: { prior_funding: "founders" } },
    ],
  },
  {
    id: "raise_amount",
    section: "financials",
    kind: "number",
    core: true,
    prompt: "How much are you looking to raise, in dollars?",
    helper: "Enter 0 if you are not raising. This is used for dilution maths, never as an input to the valuation.",
    evidence: "self_reported",
    contributes: [],
    numeric: {
      unit: "USD",
      placeholder: "e.g. 750000",
      min: 0,
      signal: "raise_usd",
      buckets: [{ max: Infinity, score: 0.5, label: "Recorded" }],
    },
  },
  {
    id: "books",
    section: "financials",
    kind: "single",
    prompt: "How are the company's accounts kept?",
    evidence: "self_reported",
    contributes: [{ factor: "financial", weight: 0.7 }],
    options: [
      { id: "accountant", label: "Accounting software, reconciled by an accountant", score: 1, evidence: "verified" },
      { id: "software", label: "Accounting software we maintain ourselves", score: 0.8, evidence: "documented" },
      { id: "spreadsheet", label: "A spreadsheet", score: 0.5, evidence: "self_reported" },
      { id: "none", label: "Nothing formal yet", score: 0.2, evidence: "estimated", signals: { no_books: true } },
    ],
  },

  /* ── Relationships & risk ─────────────────────────────────────────── */
  {
    id: "partners",
    section: "risk",
    kind: "single",
    core: true,
    prompt: "What is the most substantial outside relationship the company has?",
    evidence: "documented",
    contributes: [{ factor: "relationships", weight: 1.3 }, { factor: "gtm", weight: 0.4 }],
    options: [
      { id: "commercial", label: "A signed commercial agreement with a company that distributes or resells", score: 1, evidence: "verified" },
      { id: "pilot", label: "A paid pilot with a recognisable organisation", score: 0.9, evidence: "verified" },
      { id: "institution", label: "A research institution or accelerator we work with formally", score: 0.7, evidence: "documented" },
      { id: "advisors", label: "Advisors who give us time, without a formal agreement", score: 0.45, evidence: "self_reported" },
      { id: "none", label: "Nothing beyond our own network", score: 0.15 },
    ],
  },
  {
    id: "key_person",
    section: "risk",
    kind: "single",
    prompt: "If the single most critical person left tomorrow, what happens?",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.7 }],
    options: [
      { id: "absorb", label: "It hurts, but others can absorb the work", score: 1 },
      { id: "slow", label: "We lose several months", score: 0.6 },
      { id: "stall", label: "Development stops until we replace them", score: 0.3, signals: { key_person_risk: true } },
      { id: "fatal", label: "The company does not continue", score: 0.1, signals: { key_person_risk: true, key_person_severe: true } },
    ],
  },
  {
    id: "regulatory",
    section: "risk",
    kind: "single",
    prompt: "What does regulation require before you can sell at scale?",
    evidence: "documented",
    contributes: [{ factor: "market", weight: 0.5 }, { factor: "technology", weight: 0.3 }],
    options: [
      { id: "none", label: "Nothing specific applies to us", score: 0.9 },
      { id: "held", label: "Approvals or licences are required, and we hold them", score: 1, evidence: "verified" },
      { id: "in_progress", label: "Required, and the application is underway", score: 0.6, signals: { regulatory_pending: true } },
      { id: "not_started", label: "Required, and we have not started", score: 0.25, signals: { regulatory_risk: true } },
      { id: "unclear", label: "We are not certain what applies to us", score: 0.2, evidence: "absent", signals: { regulatory_risk: true } },
    ],
  },
  {
    id: "biggest_risk",
    section: "risk",
    kind: "rank",
    core: true,
    prompt: "Order these by how likely each is to be the thing that stops this company.",
    helper: "There is no right answer here. Founders who can name their real risk tend to be managing it.",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.5 }],
    rank: {
      items: [
        { id: "demand", label: "Nobody wants it enough to pay" },
        { id: "build", label: "We cannot build it well enough" },
        { id: "distribution", label: "We cannot reach customers affordably" },
        { id: "capital", label: "We run out of money first" },
        { id: "competition", label: "A competitor gets there first" },
        { id: "team", label: "The team does not hold together" },
      ],
      // Self-awareness, not correctness: naming demand or distribution first
      // tracks with founders who go looking for the answer.
      positionScores: {
        demand: [0.95, 0.9, 0.8, 0.7, 0.65, 0.6],
        distribution: [0.9, 0.88, 0.8, 0.7, 0.65, 0.6],
        capital: [0.7, 0.72, 0.75, 0.75, 0.7, 0.65],
        build: [0.6, 0.65, 0.7, 0.72, 0.7, 0.68],
        competition: [0.5, 0.55, 0.62, 0.7, 0.72, 0.72],
        team: [0.6, 0.62, 0.68, 0.72, 0.72, 0.7],
      },
    },
  },
  {
    id: "assumption_test",
    section: "risk",
    kind: "single",
    core: true,
    prompt: "What is the next thing you will do to test whether your riskiest assumption is true?",
    evidence: "self_reported",
    contributes: [{ factor: "team", weight: 0.8 }, { factor: "gtm", weight: 0.4 }],
    options: [
      { id: "specific_test", label: "A specific experiment is scheduled, with a number that decides it", score: 1, evidence: "documented" },
      { id: "planned", label: "We know what to test but have not designed the test", score: 0.65 },
      { id: "build_more", label: "Keep building; the assumption gets tested at launch", score: 0.4 },
      { id: "raise_first", label: "Raise money first, then test it", score: 0.3, signals: { test_deferred: true } },
      { id: "unclear", label: "We are not sure which assumption is riskiest", score: 0.15, signals: { no_risk_awareness: true } },
    ],
  },
];

export const QUESTION_BY_ID: Record<string, Question> = Object.fromEntries(
  QUESTIONS.map((q) => [q.id, q]),
);
