// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdzzmzostnlmecbwyysy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkenptem9zdG5sbWVjYnd5eXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTMzODcsImV4cCI6MjA4ODU2OTM4N30.KOI5jXsZQWz1vW_kxhXR1204mG_SrABjPjV6nyWwJ4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});